name: pharaoh
description: Fast, unopinionated, minimalist web framework for Dart. Heavily inspired by ExpressJS
version: 0.0.2
repository: https://github.com/codekeyz/pharaoh

environment:
  sdk: ^3.1.5

dependencies:
  meta: ^1.11.0
  mime: ^1.0.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  path_to_regexp: ^0.4.0
  mason_logger: ^0.2.10
  # We only need this to implement inter-operability for shelf
  shelf: ^1.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  supertest:
    path: ./supertest
