name: pharaoh_static
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  path: ^1.8.3
  pharaoh:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
